### ISSUE TITLE
Hardcoded "src" path added to :resource-paths

### ISSUE THREAD

**Issue by voytech** [adzerk-oss/bootlaces#9]
Hi,
It seems that in function bootlaces! hardcoded value "src" is always merged with resource-paths with no respect to actual env set for sources. e.g.
If we have for example following configuration:
 :source-paths   #{ "src/main/clj" "src/main/cljs" }
Then after 'build-jar' all jar entries will be as follows : "main/clj/namespace/file.clj or main/cljs/namespace/file.cljs  but should be /namespace/file.clj /namespace/file.cljs

**Comment by micha** [comment]
Ah, I see the problem.

**Comment by martinklepsch** [comment]
:+1:

**Comment by jumblerg** [comment]
i just bumped against what appears to be a related (or the same) bug while using `[adzerk/bootlaces  "0.1.13"]`; `bootlaces!` appears to have a hard dependency upon a directory named "src" in the project root, and errors when it is anything else.

**Comment by daveyarwood** [comment]
Fixed via #20
